image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull --tag tidyball .
    - docker run tidyball make check

test:
  stage: test
  script:
    - docker build --pull --tag tidyball .
    - docker run tidyball make coverage

mutants:
  stage: test
  script:
    - docker build --pull --tag tidyball .
    - docker run tidyball make mutants